(* ::Package:: *)

PacletObject[<|
    "Name" -> "Wolfram/Parser",
    "Description" -> "Parser combinators for the Wolfram Language - GrammarRules compatible, locally compiled, with a LaTeX math parser",
    "Creator" -> "Nikolay Murzin, Claude (Anthropic)",
    "PublisherID" -> "Wolfram",
    "License" -> "MIT",
    "Version" -> "1.1.3",
    "WolframVersion" -> "14.0+",
    "PrimaryContext" -> "Wolfram`Parser`",
    "Extensions" -> {
        {
            "Kernel",
            "Root" -> "Kernel",
            "Context" -> "Wolfram`Parser`",
            "Symbols" -> {
                "Wolfram`Parser`Parse",
                "Wolfram`Parser`ParsePartial",
                "Wolfram`Parser`ParserCompile",
                "Wolfram`Parser`ParserCombinator",
                "Wolfram`Parser`ParserCombinatorQ",
                "Wolfram`Parser`ParseLiteral",
                "Wolfram`Parser`ParseCharacter",
                "Wolfram`Parser`ParseRegex",
                "Wolfram`Parser`ParseSucceed",
                "Wolfram`Parser`ParseFail",
                "Wolfram`Parser`ParsePosition",
                "Wolfram`Parser`ParseSequence",
                "Wolfram`Parser`ParseChoice",
                "Wolfram`Parser`ParseMany",
                "Wolfram`Parser`ParseSome",
                "Wolfram`Parser`ParseOptional",
                "Wolfram`Parser`ParseBetween",
                "Wolfram`Parser`ParseSepBy",
                "Wolfram`Parser`ParseSepBy1",
                "Wolfram`Parser`ParseChainLeft",
                "Wolfram`Parser`ParseChainRight",
                "Wolfram`Parser`ParseOperatorTable",
                "Wolfram`Parser`ParseLookahead",
                "Wolfram`Parser`ParseNotFollowedBy",
                "Wolfram`Parser`ParseTry",
                "Wolfram`Parser`ParseRecursive",
                "Wolfram`Parser`ParseAction",
                "Wolfram`Parser`LaTeXMathParse",
                "Wolfram`Parser`LaTeXMathParser",
                "Wolfram`Parser`LaTeXMathStyle",
                "Wolfram`Parser`ExportLaTeX",
                "Wolfram`Parser`EBNFParse",
                "Wolfram`Parser`EBNFRules",
                "Wolfram`Parser`TPTPImport",
                "Wolfram`Parser`MarkdownInlineParse",
                "Wolfram`Parser`MarkdownInlineParser",
                "Wolfram`Parser`MarkdownParse",
                "Wolfram`Parser`MarkdownParser",
                "Wolfram`Parser`LeafNode",
                "Wolfram`Parser`CallNode",
                "Wolfram`Parser`PrefixNode",
                "Wolfram`Parser`PostfixNode",
                "Wolfram`Parser`BinaryNode",
                "Wolfram`Parser`InfixNode",
                "Wolfram`Parser`TernaryNode",
                "Wolfram`Parser`GroupNode",
                "Wolfram`Parser`ContainerNode",
                "Wolfram`Parser`ErrorNode",
                "Wolfram`Parser`ASTAlgebra",
                "Wolfram`Parser`ASTContainer",
                "Wolfram`Parser`ASTLeafQ",
                "Wolfram`Parser`ASTNodeQ",
                "Wolfram`Parser`ToCodeParser",
                "Wolfram`Parser`RecCell",
                "Wolfram`Parser`RecRef",
                "Wolfram`Parser`SetRec",
                "Wolfram`Parser`SpannedToken",
                "Wolfram`Parser`ASTAddSource",
                "Wolfram`Parser`ASTStripSource",
                "Wolfram`Parser`ParseChoiceLongest",
                "Wolfram`Parser`TPTPExport",
                "Wolfram`Parser`Languages`Calculator`CalculatorAST",
                "Wolfram`Parser`Languages`Calculator`CalculatorEval",
                "Wolfram`Parser`Languages`Calculator`CalculatorGrammar",
                "Wolfram`Parser`Languages`Calculator`CalculatorSemantic",
                "Wolfram`Parser`Languages`JSON`JSONAST",
                "Wolfram`Parser`Languages`JSON`JSONGrammar",
                "Wolfram`Parser`Languages`JSON`JSONImport",
                "Wolfram`Parser`Languages`JSON`JSONSemantic",
                "Wolfram`Parser`Languages`Lisp`LispAST",
                "Wolfram`Parser`Languages`Lisp`LispGrammar",
                "Wolfram`Parser`Languages`Lisp`LispRead",
                "Wolfram`Parser`Languages`Lisp`LispSemantic",
                "Wolfram`Parser`Languages`Lisp`LispSymbol",
                "Wolfram`Parser`Languages`Lambda`LambdaAST",
                "Wolfram`Parser`Languages`Lambda`LambdaEval",
                "Wolfram`Parser`Languages`Lambda`LambdaGrammar",
                "Wolfram`Parser`Languages`Lambda`LambdaSemantic",
                "Wolfram`Parser`Languages`Brainfuck`BrainfuckAST",
                "Wolfram`Parser`Languages`Brainfuck`BrainfuckGrammar",
                "Wolfram`Parser`Languages`Brainfuck`BrainfuckRun",
                "Wolfram`Parser`Languages`Brainfuck`BrainfuckSemantic"
            }
        },
        {
            "Asset",
            "Root" -> "Assets",
            "Assets" -> {
                {"CompiledLaTeXParser", "LaTeXMathParserCompiled.wxf"},
                {"Hero", "hero.png"}
            }
        },
        {
            "Documentation",
            "Language" -> "English"
        }
    }
|>]
